# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: course.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'course.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ourse.proto\x12\x0e\x63ourse_service\"V\n\x06\x43ourse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x12\n\ninstructor\x18\x04 \x01(\t\x12\x10\n\x08\x63\x61pacity\x18\x05 \x01(\x05\"\x07\n\x05\x45mpty\"P\n\x0c\x43ourseCreate\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\ninstructor\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61pacity\x18\x04 \x01(\x05\"V\n\x13UpdateCourseRequest\x12\x11\n\tcourse_id\x18\x01 \x01(\x05\x12,\n\x06\x63ourse\x18\x02 \x01(\x0b\x32\x1c.course_service.CourseCreate\"(\n\x13\x44\x65leteCourseRequest\x12\x11\n\tcourse_id\x18\x01 \x01(\x05\"\'\n\x14\x44\x65leteCourseResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\">\n\x13ListCoursesResponse\x12\'\n\x07\x63ourses\x18\x01 \x03(\x0b\x32\x16.course_service.Course2\xc8\x02\n\rCourseService\x12I\n\x0bListCourses\x12\x15.course_service.Empty\x1a#.course_service.ListCoursesResponse\x12\x44\n\x0c\x43reateCourse\x12\x1c.course_service.CourseCreate\x1a\x16.course_service.Course\x12K\n\x0cUpdateCourse\x12#.course_service.UpdateCourseRequest\x1a\x16.course_service.Course\x12Y\n\x0c\x44\x65leteCourse\x12#.course_service.DeleteCourseRequest\x1a$.course_service.DeleteCourseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'course_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COURSE']._serialized_start=32
  _globals['_COURSE']._serialized_end=118
  _globals['_EMPTY']._serialized_start=120
  _globals['_EMPTY']._serialized_end=127
  _globals['_COURSECREATE']._serialized_start=129
  _globals['_COURSECREATE']._serialized_end=209
  _globals['_UPDATECOURSEREQUEST']._serialized_start=211
  _globals['_UPDATECOURSEREQUEST']._serialized_end=297
  _globals['_DELETECOURSEREQUEST']._serialized_start=299
  _globals['_DELETECOURSEREQUEST']._serialized_end=339
  _globals['_DELETECOURSERESPONSE']._serialized_start=341
  _globals['_DELETECOURSERESPONSE']._serialized_end=380
  _globals['_LISTCOURSESRESPONSE']._serialized_start=382
  _globals['_LISTCOURSESRESPONSE']._serialized_end=444
  _globals['_COURSESERVICE']._serialized_start=447
  _globals['_COURSESERVICE']._serialized_end=775
# @@protoc_insertion_point(module_scope)
