# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enrollment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'enrollment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65nrollment.proto\x12\x12\x65nrollment_service\"V\n\x06\x43ourse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x12\n\ninstructor\x18\x04 \x01(\t\x12\x10\n\x08\x63\x61pacity\x18\x05 \x01(\x05\"\x07\n\x05\x45mpty\"=\n\x14\x45nrollStudentRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\x05\x12\x11\n\tcourse_id\x18\x02 \x01(\x05\")\n\x15\x45nrollStudentResponse\x12\x10\n\x08\x65nrolled\x18\x01 \x01(\x08\"B\n\x13ListCoursesResponse\x12+\n\x07\x63ourses\x18\x01 \x03(\x0b\x32\x1a.enrollment_service.Course2\xcc\x01\n\x11\x45nrollmentService\x12Q\n\x0bListCourses\x12\x19.enrollment_service.Empty\x1a\'.enrollment_service.ListCoursesResponse\x12\x64\n\rEnrollStudent\x12(.enrollment_service.EnrollStudentRequest\x1a).enrollment_service.EnrollStudentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enrollment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COURSE']._serialized_start=40
  _globals['_COURSE']._serialized_end=126
  _globals['_EMPTY']._serialized_start=128
  _globals['_EMPTY']._serialized_end=135
  _globals['_ENROLLSTUDENTREQUEST']._serialized_start=137
  _globals['_ENROLLSTUDENTREQUEST']._serialized_end=198
  _globals['_ENROLLSTUDENTRESPONSE']._serialized_start=200
  _globals['_ENROLLSTUDENTRESPONSE']._serialized_end=241
  _globals['_LISTCOURSESRESPONSE']._serialized_start=243
  _globals['_LISTCOURSESRESPONSE']._serialized_end=309
  _globals['_ENROLLMENTSERVICE']._serialized_start=312
  _globals['_ENROLLMENTSERVICE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
