# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\'\n\x0eRefreshRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"&\n\rLogoutRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"V\n\x05Token\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\ntoken_type\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x15\n\rrefresh_token\x18\x04 \x01(\t\"\x1c\n\x0eLogoutResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x9a\x01\n\x0b\x41uthService\x12(\n\x05Login\x12\x12.auth.LoginRequest\x1a\x0b.auth.Token\x12,\n\x07Refresh\x12\x14.auth.RefreshRequest\x1a\x0b.auth.Token\x12\x33\n\x06Logout\x12\x13.auth.LogoutRequest\x1a\x14.auth.LogoutResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=20
  _globals['_LOGINREQUEST']._serialized_end=70
  _globals['_REFRESHREQUEST']._serialized_start=72
  _globals['_REFRESHREQUEST']._serialized_end=111
  _globals['_LOGOUTREQUEST']._serialized_start=113
  _globals['_LOGOUTREQUEST']._serialized_end=151
  _globals['_TOKEN']._serialized_start=153
  _globals['_TOKEN']._serialized_end=239
  _globals['_LOGOUTRESPONSE']._serialized_start=241
  _globals['_LOGOUTRESPONSE']._serialized_end=269
  _globals['_AUTHSERVICE']._serialized_start=272
  _globals['_AUTHSERVICE']._serialized_end=426
# @@protoc_insertion_point(module_scope)
