# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import course_pb2 as course__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in course_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CourseServiceStub(object):
    """gRPC service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCourses = channel.unary_unary(
                '/course_service.CourseService/ListCourses',
                request_serializer=course__pb2.Empty.SerializeToString,
                response_deserializer=course__pb2.ListCoursesResponse.FromString,
                _registered_method=True)
        self.CreateCourse = channel.unary_unary(
                '/course_service.CourseService/CreateCourse',
                request_serializer=course__pb2.CourseCreate.SerializeToString,
                response_deserializer=course__pb2.Course.FromString,
                _registered_method=True)
        self.UpdateCourse = channel.unary_unary(
                '/course_service.CourseService/UpdateCourse',
                request_serializer=course__pb2.UpdateCourseRequest.SerializeToString,
                response_deserializer=course__pb2.Course.FromString,
                _registered_method=True)
        self.DeleteCourse = channel.unary_unary(
                '/course_service.CourseService/DeleteCourse',
                request_serializer=course__pb2.DeleteCourseRequest.SerializeToString,
                response_deserializer=course__pb2.DeleteCourseResponse.FromString,
                _registered_method=True)


class CourseServiceServicer(object):
    """gRPC service definition
    """

    def ListCourses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCourse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCourse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCourse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CourseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCourses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCourses,
                    request_deserializer=course__pb2.Empty.FromString,
                    response_serializer=course__pb2.ListCoursesResponse.SerializeToString,
            ),
            'CreateCourse': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCourse,
                    request_deserializer=course__pb2.CourseCreate.FromString,
                    response_serializer=course__pb2.Course.SerializeToString,
            ),
            'UpdateCourse': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCourse,
                    request_deserializer=course__pb2.UpdateCourseRequest.FromString,
                    response_serializer=course__pb2.Course.SerializeToString,
            ),
            'DeleteCourse': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCourse,
                    request_deserializer=course__pb2.DeleteCourseRequest.FromString,
                    response_serializer=course__pb2.DeleteCourseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'course_service.CourseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('course_service.CourseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CourseService(object):
    """gRPC service definition
    """

    @staticmethod
    def ListCourses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/course_service.CourseService/ListCourses',
            course__pb2.Empty.SerializeToString,
            course__pb2.ListCoursesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCourse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/course_service.CourseService/CreateCourse',
            course__pb2.CourseCreate.SerializeToString,
            course__pb2.Course.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCourse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/course_service.CourseService/UpdateCourse',
            course__pb2.UpdateCourseRequest.SerializeToString,
            course__pb2.Course.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCourse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/course_service.CourseService/DeleteCourse',
            course__pb2.DeleteCourseRequest.SerializeToString,
            course__pb2.DeleteCourseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
