# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import enrollment_pb2 as enrollment__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in enrollment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EnrollmentServiceStub(object):
    """gRPC service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCourses = channel.unary_unary(
                '/enrollment_service.EnrollmentService/ListCourses',
                request_serializer=enrollment__pb2.Empty.SerializeToString,
                response_deserializer=enrollment__pb2.ListCoursesResponse.FromString,
                _registered_method=True)
        self.EnrollStudent = channel.unary_unary(
                '/enrollment_service.EnrollmentService/EnrollStudent',
                request_serializer=enrollment__pb2.EnrollStudentRequest.SerializeToString,
                response_deserializer=enrollment__pb2.EnrollStudentResponse.FromString,
                _registered_method=True)


class EnrollmentServiceServicer(object):
    """gRPC service definition
    """

    def ListCourses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrollStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnrollmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCourses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCourses,
                    request_deserializer=enrollment__pb2.Empty.FromString,
                    response_serializer=enrollment__pb2.ListCoursesResponse.SerializeToString,
            ),
            'EnrollStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrollStudent,
                    request_deserializer=enrollment__pb2.EnrollStudentRequest.FromString,
                    response_serializer=enrollment__pb2.EnrollStudentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'enrollment_service.EnrollmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('enrollment_service.EnrollmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnrollmentService(object):
    """gRPC service definition
    """

    @staticmethod
    def ListCourses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrollment_service.EnrollmentService/ListCourses',
            enrollment__pb2.Empty.SerializeToString,
            enrollment__pb2.ListCoursesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrollStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrollment_service.EnrollmentService/EnrollStudent',
            enrollment__pb2.EnrollStudentRequest.SerializeToString,
            enrollment__pb2.EnrollStudentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
