# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grades.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grades.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgrades.proto\x12\x06grades\"5\n\nGradeEntry\x12\x12\n\nstudent_id\x18\x01 \x01(\x05\x12\x13\n\x0bgrade_value\x18\x02 \x01(\t\"2\n\x0bGradeUpload\x12#\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x12.grades.GradeEntry\"\x8f\x01\n\tGradeRead\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nstudent_id\x18\x02 \x01(\x05\x12\x11\n\tcourse_id\x18\x03 \x01(\x05\x12\x13\n\x0bgrade_value\x18\x04 \x01(\t\x12\x10\n\x08semester\x18\x05 \x01(\t\x12\x13\n\x0buploaded_by\x18\x06 \x01(\x05\x12\x13\n\x0buploaded_at\x18\x07 \x01(\t\"c\n\x13UploadGradesRequest\x12\x11\n\tcourse_id\x18\x01 \x01(\x05\x12$\n\x07payload\x18\x02 \x01(\x0b\x32\x13.grades.GradeUpload\x12\x13\n\x0buploaded_by\x18\x03 \x01(\x05\"\'\n\x14UploadGradesResponse\x12\x0f\n\x07\x63reated\x18\x01 \x01(\x05\"&\n\x10GetGradesRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\x05\"6\n\x11GetGradesResponse\x12!\n\x06grades\x18\x01 \x03(\x0b\x32\x11.grades.GradeRead2\x9e\x01\n\rGradesService\x12I\n\x0cUploadGrades\x12\x1b.grades.UploadGradesRequest\x1a\x1c.grades.UploadGradesResponse\x12\x42\n\x0bGetMyGrades\x12\x18.grades.GetGradesRequest\x1a\x19.grades.GetGradesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grades_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRADEENTRY']._serialized_start=24
  _globals['_GRADEENTRY']._serialized_end=77
  _globals['_GRADEUPLOAD']._serialized_start=79
  _globals['_GRADEUPLOAD']._serialized_end=129
  _globals['_GRADEREAD']._serialized_start=132
  _globals['_GRADEREAD']._serialized_end=275
  _globals['_UPLOADGRADESREQUEST']._serialized_start=277
  _globals['_UPLOADGRADESREQUEST']._serialized_end=376
  _globals['_UPLOADGRADESRESPONSE']._serialized_start=378
  _globals['_UPLOADGRADESRESPONSE']._serialized_end=417
  _globals['_GETGRADESREQUEST']._serialized_start=419
  _globals['_GETGRADESREQUEST']._serialized_end=457
  _globals['_GETGRADESRESPONSE']._serialized_start=459
  _globals['_GETGRADESRESPONSE']._serialized_end=513
  _globals['_GRADESSERVICE']._serialized_start=516
  _globals['_GRADESSERVICE']._serialized_end=674
# @@protoc_insertion_point(module_scope)
