# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"l\n\x08UserRead\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x11\n\tis_active\x18\x05 \x01(\x08\x12\x12\n\ncreated_at\x18\x06 \x01(\t\"M\n\nUserCreate\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\"H\n\nUserUpdate\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x11\n\tis_active\x18\x04 \x01(\x08\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\x12\n\x10ListUsersRequest\"3\n\x11ListUsersResponse\x12\x1e\n\x05users\x18\x01 \x03(\x0b\x32\x0f.users.UserRead\"3\n\x12\x43reateUserResponse\x12\x1d\n\x04user\x18\x01 \x01(\x0b\x32\x0f.users.UserRead\"4\n\x11UpdateUserRequest\x12\x1f\n\x04user\x18\x01 \x01(\x0b\x32\x11.users.UserUpdate\"3\n\x12UpdateUserResponse\x12\x1d\n\x04user\x18\x01 \x01(\x0b\x32\x0f.users.UserRead\"$\n\x11\x44\x65leteUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"%\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\x32\xc3\x02\n\x0cUsersService\x12\x31\n\x07GetUser\x12\x15.users.GetUserRequest\x1a\x0f.users.UserRead\x12>\n\tListUsers\x12\x17.users.ListUsersRequest\x1a\x18.users.ListUsersResponse\x12:\n\nCreateUser\x12\x11.users.UserCreate\x1a\x19.users.CreateUserResponse\x12\x41\n\nUpdateUser\x12\x18.users.UpdateUserRequest\x1a\x19.users.UpdateUserResponse\x12\x41\n\nDeleteUser\x12\x18.users.DeleteUserRequest\x1a\x19.users.DeleteUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREAD']._serialized_start=22
  _globals['_USERREAD']._serialized_end=130
  _globals['_USERCREATE']._serialized_start=132
  _globals['_USERCREATE']._serialized_end=209
  _globals['_USERUPDATE']._serialized_start=211
  _globals['_USERUPDATE']._serialized_end=283
  _globals['_GETUSERREQUEST']._serialized_start=285
  _globals['_GETUSERREQUEST']._serialized_end=318
  _globals['_LISTUSERSREQUEST']._serialized_start=320
  _globals['_LISTUSERSREQUEST']._serialized_end=338
  _globals['_LISTUSERSRESPONSE']._serialized_start=340
  _globals['_LISTUSERSRESPONSE']._serialized_end=391
  _globals['_CREATEUSERRESPONSE']._serialized_start=393
  _globals['_CREATEUSERRESPONSE']._serialized_end=444
  _globals['_UPDATEUSERREQUEST']._serialized_start=446
  _globals['_UPDATEUSERREQUEST']._serialized_end=498
  _globals['_UPDATEUSERRESPONSE']._serialized_start=500
  _globals['_UPDATEUSERRESPONSE']._serialized_end=551
  _globals['_DELETEUSERREQUEST']._serialized_start=553
  _globals['_DELETEUSERREQUEST']._serialized_end=589
  _globals['_DELETEUSERRESPONSE']._serialized_start=591
  _globals['_DELETEUSERRESPONSE']._serialized_end=628
  _globals['_USERSSERVICE']._serialized_start=631
  _globals['_USERSSERVICE']._serialized_end=954
# @@protoc_insertion_point(module_scope)
