# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: course_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'course_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63ourse_service.proto\x12\rcourseservice\"\x07\n\x05\x45mpty\"\"\n\rCourseRequest\x12\x11\n\tcourse_id\x18\x01 \x01(\x05\"p\n\x0c\x43ourseRecord\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x12\n\ninstructor\x18\x04 \x01(\t\x12\x10\n\x08\x63\x61pacity\x18\x05 \x01(\x05\x12\x12\n\ncreated_at\x18\x06 \x01(\x03\"N\n\x0f\x43oursesResponse\x12,\n\x07\x63ourses\x18\x01 \x03(\x0b\x32\x1b.courseservice.CourseRecord\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"W\n\x13\x43ourseCreateRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\ninstructor\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61pacity\x18\x04 \x01(\x05\"c\n\x13\x43ourseUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x12\n\ninstructor\x18\x04 \x01(\t\x12\x10\n\x08\x63\x61pacity\x18\x05 \x01(\x05\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8b\x03\n\rCourseService\x12\x43\n\x0bListCourses\x12\x14.courseservice.Empty\x1a\x1e.courseservice.CoursesResponse\x12\x46\n\tGetCourse\x12\x1c.courseservice.CourseRequest\x1a\x1b.courseservice.CourseRecord\x12O\n\x0c\x43reateCourse\x12\".courseservice.CourseCreateRequest\x1a\x1b.courseservice.CourseRecord\x12O\n\x0cUpdateCourse\x12\".courseservice.CourseUpdateRequest\x1a\x1b.courseservice.CourseRecord\x12K\n\x0c\x44\x65leteCourse\x12\x1c.courseservice.CourseRequest\x1a\x1d.courseservice.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'course_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=39
  _globals['_EMPTY']._serialized_end=46
  _globals['_COURSEREQUEST']._serialized_start=48
  _globals['_COURSEREQUEST']._serialized_end=82
  _globals['_COURSERECORD']._serialized_start=84
  _globals['_COURSERECORD']._serialized_end=196
  _globals['_COURSESRESPONSE']._serialized_start=198
  _globals['_COURSESRESPONSE']._serialized_end=276
  _globals['_COURSECREATEREQUEST']._serialized_start=278
  _globals['_COURSECREATEREQUEST']._serialized_end=365
  _globals['_COURSEUPDATEREQUEST']._serialized_start=367
  _globals['_COURSEUPDATEREQUEST']._serialized_end=466
  _globals['_DELETERESPONSE']._serialized_start=468
  _globals['_DELETERESPONSE']._serialized_end=518
  _globals['_COURSESERVICE']._serialized_start=521
  _globals['_COURSESERVICE']._serialized_end=916
# @@protoc_insertion_point(module_scope)
