# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import grade_service_pb2 as grade__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grade_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GradeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStudentGrades = channel.unary_unary(
                '/gradeservice.GradeService/GetStudentGrades',
                request_serializer=grade__service__pb2.GetGradesRequest.SerializeToString,
                response_deserializer=grade__service__pb2.GradesResponse.FromString,
                _registered_method=True)
        self.UploadGrades = channel.unary_unary(
                '/gradeservice.GradeService/UploadGrades',
                request_serializer=grade__service__pb2.UploadGradesRequest.SerializeToString,
                response_deserializer=grade__service__pb2.UploadGradesResponse.FromString,
                _registered_method=True)
        self.StreamStudentGrades = channel.unary_stream(
                '/gradeservice.GradeService/StreamStudentGrades',
                request_serializer=grade__service__pb2.GetGradesByStudentRequest.SerializeToString,
                response_deserializer=grade__service__pb2.GradeRecord.FromString,
                _registered_method=True)


class GradeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStudentGrades(self, request, context):
        """Get grades for a specific student
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadGrades(self, request, context):
        """Upload grades for a course (internal gRPC only)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStudentGrades(self, request, context):
        """Stream grades for a student (for large datasets)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GradeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStudentGrades': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudentGrades,
                    request_deserializer=grade__service__pb2.GetGradesRequest.FromString,
                    response_serializer=grade__service__pb2.GradesResponse.SerializeToString,
            ),
            'UploadGrades': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadGrades,
                    request_deserializer=grade__service__pb2.UploadGradesRequest.FromString,
                    response_serializer=grade__service__pb2.UploadGradesResponse.SerializeToString,
            ),
            'StreamStudentGrades': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStudentGrades,
                    request_deserializer=grade__service__pb2.GetGradesByStudentRequest.FromString,
                    response_serializer=grade__service__pb2.GradeRecord.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gradeservice.GradeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gradeservice.GradeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GradeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStudentGrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gradeservice.GradeService/GetStudentGrades',
            grade__service__pb2.GetGradesRequest.SerializeToString,
            grade__service__pb2.GradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadGrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gradeservice.GradeService/UploadGrades',
            grade__service__pb2.UploadGradesRequest.SerializeToString,
            grade__service__pb2.UploadGradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStudentGrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gradeservice.GradeService/StreamStudentGrades',
            grade__service__pb2.GetGradesByStudentRequest.SerializeToString,
            grade__service__pb2.GradeRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
