# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grade_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grade_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13grade_service.proto\x12\x0cgradeservice\"&\n\x10GetGradesRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\x05\"\xa9\x01\n\x0bGradeRecord\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nstudent_id\x18\x02 \x01(\x05\x12\x11\n\tcourse_id\x18\x03 \x01(\x05\x12\x13\n\x0bgrade_value\x18\x04 \x01(\t\x12\x13\n\x0b\x63ourse_code\x18\x05 \x01(\t\x12\x13\n\x0b\x63ourse_name\x18\x06 \x01(\t\x12\x13\n\x0buploaded_at\x18\x07 \x01(\x03\x12\x13\n\x0buploaded_by\x18\x08 \x01(\x05\"J\n\x0eGradesResponse\x12)\n\x06grades\x18\x01 \x03(\x0b\x32\x19.gradeservice.GradeRecord\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"h\n\x13UploadGradesRequest\x12\x11\n\tcourse_id\x18\x01 \x01(\x05\x12\x13\n\x0buploaded_by\x18\x02 \x01(\x05\x12)\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x18.gradeservice.GradeEntry\"5\n\nGradeEntry\x12\x12\n\nstudent_id\x18\x01 \x01(\x05\x12\x13\n\x0bgrade_value\x18\x02 \x01(\t\"O\n\x14UploadGradesResponse\x12\x15\n\rcreated_count\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"/\n\x19GetGradesByStudentRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\x05\x32\x94\x02\n\x0cGradeService\x12P\n\x10GetStudentGrades\x12\x1e.gradeservice.GetGradesRequest\x1a\x1c.gradeservice.GradesResponse\x12U\n\x0cUploadGrades\x12!.gradeservice.UploadGradesRequest\x1a\".gradeservice.UploadGradesResponse\x12[\n\x13StreamStudentGrades\x12\'.gradeservice.GetGradesByStudentRequest\x1a\x19.gradeservice.GradeRecord0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grade_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETGRADESREQUEST']._serialized_start=37
  _globals['_GETGRADESREQUEST']._serialized_end=75
  _globals['_GRADERECORD']._serialized_start=78
  _globals['_GRADERECORD']._serialized_end=247
  _globals['_GRADESRESPONSE']._serialized_start=249
  _globals['_GRADESRESPONSE']._serialized_end=323
  _globals['_UPLOADGRADESREQUEST']._serialized_start=325
  _globals['_UPLOADGRADESREQUEST']._serialized_end=429
  _globals['_GRADEENTRY']._serialized_start=431
  _globals['_GRADEENTRY']._serialized_end=484
  _globals['_UPLOADGRADESRESPONSE']._serialized_start=486
  _globals['_UPLOADGRADESRESPONSE']._serialized_end=565
  _globals['_GETGRADESBYSTUDENTREQUEST']._serialized_start=567
  _globals['_GETGRADESBYSTUDENTREQUEST']._serialized_end=614
  _globals['_GRADESERVICE']._serialized_start=617
  _globals['_GRADESERVICE']._serialized_end=893
# @@protoc_insertion_point(module_scope)
