# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x0buserservice\"\x07\n\x05\x45mpty\"1\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"f\n\x0c\x41uthResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12%\n\x04user\x18\x02 \x01(\x0b\x32\x17.userservice.UserRecord\x12\r\n\x05token\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"T\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\"[\n\nUserRecord\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\x03\"F\n\rUsersResponse\x12&\n\x05users\x18\x01 \x03(\x0b\x32\x17.userservice.UserRecord\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x32\x98\x02\n\x0bUserService\x12G\n\x10\x41uthenticateUser\x12\x18.userservice.AuthRequest\x1a\x19.userservice.AuthResponse\x12<\n\x07GetUser\x12\x18.userservice.UserRequest\x1a\x17.userservice.UserRecord\x12;\n\tListUsers\x12\x12.userservice.Empty\x1a\x1a.userservice.UsersResponse\x12\x45\n\nCreateUser\x12\x1e.userservice.CreateUserRequest\x1a\x17.userservice.UserRecordb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=35
  _globals['_EMPTY']._serialized_end=42
  _globals['_AUTHREQUEST']._serialized_start=44
  _globals['_AUTHREQUEST']._serialized_end=93
  _globals['_AUTHRESPONSE']._serialized_start=95
  _globals['_AUTHRESPONSE']._serialized_end=197
  _globals['_USERREQUEST']._serialized_start=199
  _globals['_USERREQUEST']._serialized_end=229
  _globals['_CREATEUSERREQUEST']._serialized_start=231
  _globals['_CREATEUSERREQUEST']._serialized_end=315
  _globals['_USERRECORD']._serialized_start=317
  _globals['_USERRECORD']._serialized_end=408
  _globals['_USERSRESPONSE']._serialized_start=410
  _globals['_USERSRESPONSE']._serialized_end=480
  _globals['_USERSERVICE']._serialized_start=483
  _globals['_USERSERVICE']._serialized_end=763
# @@protoc_insertion_point(module_scope)
