# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import grades_pb2 as grades__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grades_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GradesServiceStub(object):
    """--- Service ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadGrades = channel.unary_unary(
                '/grades.GradesService/UploadGrades',
                request_serializer=grades__pb2.UploadGradesRequest.SerializeToString,
                response_deserializer=grades__pb2.UploadGradesResponse.FromString,
                _registered_method=True)
        self.GetMyGrades = channel.unary_unary(
                '/grades.GradesService/GetMyGrades',
                request_serializer=grades__pb2.GetGradesRequest.SerializeToString,
                response_deserializer=grades__pb2.GetGradesResponse.FromString,
                _registered_method=True)


class GradesServiceServicer(object):
    """--- Service ---

    """

    def UploadGrades(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMyGrades(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GradesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadGrades': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadGrades,
                    request_deserializer=grades__pb2.UploadGradesRequest.FromString,
                    response_serializer=grades__pb2.UploadGradesResponse.SerializeToString,
            ),
            'GetMyGrades': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMyGrades,
                    request_deserializer=grades__pb2.GetGradesRequest.FromString,
                    response_serializer=grades__pb2.GetGradesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grades.GradesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grades.GradesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GradesService(object):
    """--- Service ---

    """

    @staticmethod
    def UploadGrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grades.GradesService/UploadGrades',
            grades__pb2.UploadGradesRequest.SerializeToString,
            grades__pb2.UploadGradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMyGrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grades.GradesService/GetMyGrades',
            grades__pb2.GetGradesRequest.SerializeToString,
            grades__pb2.GetGradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
